<% 
def get_mysql_password
  `python -c 'import ConfigParser; p = ConfigParser.SafeConfigParser(); p.read("#{ENV['HOME']}/.my.cnf"); print p.get("mysql", "password")'`
end
%>

mysql: &mysql
  adapter: mysql
  username: root
  password: <%= get_mysql_password %>
  host: localhost
  socket: <%= [
    '/var/lib/mysql/mysql.sock',
    '/var/run/mysqld/mysqld.sock',
    '/tmp/mysqld.sock',
    '/tmp/mysql.sock',
  ].detect { |socket| File.exist?(socket) } %>

development:
  database: jr_development
  <<: *mysql

test: &test
  database: jr_test
  <<: *mysql

production:
  database: jr_production
  <<: *mysql
